import Proofs.OmegaCompletePartialOrder.Chain
import Proofs.OmegaCompletePartialOrder.ContinuousHom
import Proofs.OmegaCompletePartialOrder.Instances
import Proofs.OmegaCompletePartialOrder.OmegaScottContinuity
